# Generated by Django 5.0.1 on 2024-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_order_orderitem_review_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
